Add custom icons and fonts #25
Emmanuel-Melon/sahil pull request #27
Opened 2023-08-24 22:20 UTC by mde3

Installed react-icons, added custom favicon file and switched Inter font to Montserrat

Also added few files into tailwind config file

2023-08-25 05:31 UTC, Emmanuel-Melon requested changes
Looks good!

2023-08-25 05:31 UTC, Emmanuel-Melon commented on yarn.lock
> +  resolved "https://registry.yarnpkg.com/react-icons/-/react-icons-4.10.1.tgz#3f3b5eec1f63c1796f6a26174a1091ca6437a500"
Which react-icons subset will you use? I think it's better to install it separately due to its large size.

2023-08-25 05:31 UTC, Emmanuel-Melon commented on apps/agent/src/styles/globals.css
> +    @apply bg-[theme("colors.greenDark")];
Can't we customize these from the tailwind config file? It's recommended to maintain a single source of truth for config files.

2023-08-25 08:01 UTC, mde3 commented on yarn.lock
> +  resolved "https://registry.yarnpkg.com/react-icons/-/react-icons-4.10.1.tgz#3f3b5eec1f63c1796f6a26174a1091ca6437a500"
That's the beauty of react-icons, it offers a comprehensive collection of icons from various subsets, providing you with a wide selection to choose from without being restricted to a single subset

For example, to pick an icon from font awesome subset, you would look for the icon and define its subset when importing it i.e :
**import { ICON_NAME } from 'react-icons/fa'**  

Similarly to import box icons:
**import { ICON_NAME } from 'react-icons/bi'**  

**fa** - subset for font awesome icons
**bi** - subset for box icons

2023-08-25 08:07 UTC, Emmanuel-Melon commented on yarn.lock
> +  resolved "https://registry.yarnpkg.com/react-icons/-/react-icons-4.10.1.tgz#3f3b5eec1f63c1796f6a26174a1091ca6437a500"
I think using just one subset would be better for a consistent design. Could you check if react-icons only imports what we need? Otherwise, it might make the bundle size really big.

2023-08-25 08:44 UTC, mde3 commented on apps/agent/src/styles/globals.css
> +    @apply bg-[theme("colors.greenDark")];
I totally agree. The reason behind why I included these in the global css file and not all in the tailwind config file was because they are custom utility classes for various elements throughout the project.

Another reason is that it's not possible for some of these custom utility classes to be defined directly into the tailwind config file. That's where the global css file comes to play by helping us extend Tailwind CSS with your own custom utility classes.

One of them being a button as an example, we can define what we want the button to look like from here throughout the project.

But most importantly, it was because of the font size. I set in a way such that at different screen sizes, the font size will increase accordingly

2023-08-25 08:57 UTC, mde3 commented on yarn.lock
> +  resolved "https://registry.yarnpkg.com/react-icons/-/react-icons-4.10.1.tgz#3f3b5eec1f63c1796f6a26174a1091ca6437a500"
Yes react-icons only imports icons that you need for a project as it utilizes ES6 imports which allows you to include only the subset you select.

This can help reduce the size of the bundle and improve performance of the app.  So if we only choose font awesome subset then we'd eliminate bundle getting really big and maintain consistent design as well

If it's still an issue, what icon library would you recommend? React-icons has been my go-to, haven't really used other libraries

2023-08-25 11:46 UTC, Emmanuel-Melon commented on apps/agent/src/styles/globals.css
> +    @apply bg-[theme("colors.greenDark")];
We can leave some globally applicable styles here. For the buttons, we can create a reusable button component.

2023-08-25 11:47 UTC, Emmanuel-Melon commented on yarn.lock
> +  resolved "https://registry.yarnpkg.com/react-icons/-/react-icons-4.10.1.tgz#3f3b5eec1f63c1796f6a26174a1091ca6437a500"
All good, just wanted a confirmation!

2023-08-25 16:38 UTC, mde3 commented on yarn.lock
> +  resolved "https://registry.yarnpkg.com/react-icons/-/react-icons-4.10.1.tgz#3f3b5eec1f63c1796f6a26174a1091ca6437a500"
Yeah sure no worries

2023-08-25 16:39 UTC, mde3 commented on apps/agent/src/styles/globals.css
> +    @apply bg-[theme("colors.greenDark")];
Alright

2023-08-26 11:49 UTC, Emmanuel-Melon commented
@mde3 resolve the merge conflict and we'll be good to go!

2024-01-05 11:54 UTC, TrevorNyan commented
@mde3 is this feature still relevant?

2024-01-05 12:08 UTC, Emmanuel-Melon commented
> @mde3 is this PR still relevant?

Nopes

2024-01-05 12:08 UTC, closed without merging